
fragment documentationFields on Documentation {
    documentations {
        documentation
        attribution {
            time
            actor {
                urn
                type
                ...entityDisplayNameFields
            }
            source {
                urn
                type
            }
            sourceDetail {
                key
                value
            }
        }
    }
}


fragment businessAttribute on BusinessAttributeAssociation {
    businessAttribute {
        urn
        type
        ownership {
            ...ownershipFields
        }
        properties {
            name
            description
            businessAttributeDataType: type
            lastModified {
                time
            }
            created {
                time
            }
            tags {
                tags {
                    tag {
                        urn
                        name
                        properties {
                            name
                        }
                    }
                    associatedUrn
                }
            }
            glossaryTerms {
                terms {
                    term {
                        urn
                        type
                        properties {
                            name
                        }
                    }
                    associatedUrn
                }
            }
        }
    }
    associatedUrn
}

fragment structuredPropertyFields on StructuredPropertyEntity {
    urn
    type
    definition {
        displayName
        qualifiedName
        description
        cardinality
        immutable
        valueType {
            urn
            type
            info {
                type
                displayName
            }
        }
        entityTypes {
            urn
            type
            info {
                type
            }
        }
        cardinality
        typeQualifier {
            allowedTypes {
                urn
                type
                info {
                    type
                    displayName
                }
            }
        }
        allowedValues {
            value {
                ... on StringValue {
                    stringValue
                }
                ... on NumberValue {
                    numberValue
                }
            }
            description
        }
        created {
            time
            actor {
                urn
                editableProperties {
                    displayName
                    pictureLink
                }
                ...entityDisplayNameFields
            }
        }
        lastModified {
            time
            actor {
                urn
                editableProperties {
                    displayName
                    pictureLink
                }
                ...entityDisplayNameFields
            }
        }
    }
    settings {
        isHidden
        showInSearchFilters
        showAsAssetBadge
        showInAssetSummary
        showInColumnsTable
    }
}

fragment structuredPropertiesFields on StructuredPropertiesEntry {
    structuredProperty {
        exists
        ...structuredPropertyFields
    }
    values {
        ... on StringValue {
            stringValue
        }
        ... on NumberValue {
            numberValue
        }
    }
    valueEntities {
        urn
        type
        ...entityDisplayNameFields
    }
    associatedUrn
}

fragment entitySchemaFieldEntityFields on SchemaFieldEntity {
#    deprecation {
#        ...deprecationFields
#    }
    urn
    fieldPath
    type
    structuredProperties {
        properties {
            ...structuredPropertiesFields
        }
    }
    businessAttributes {
        businessAttribute {
            ...businessAttribute
        }
    }
    documentation {
        ...documentationFields
    }
}

fragment entitySchemaFieldFields on SchemaField {
    fieldPath
    label
    jsonPath
    nullable
    description
    type
    nativeDataType
    recursive
    isPartOfKey
    isPartitioningKey
    globalTags {
        ...globalTagsFields
    }
    glossaryTerms {
        ...glossaryTerms
    }
    schemaFieldEntity {
        ...entitySchemaFieldEntityFields
    }
}

fragment schemaMetadataFields on SchemaMetadata {
    aspectVersion
    createdAt
    datasetUrn
    name
    platformUrn
    version
    cluster
    hash
    platformSchema {
        ... on TableSchema {
            schema
        }
        ... on KeyValueSchema {
            keySchema
            valueSchema
        }
    }
    fields {
        ...entitySchemaFieldFields
    }
    primaryKeys
    foreignKeys {
        name
        sourceFields {
            fieldPath
        }
        foreignFields {
            fieldPath
        }
        foreignDataset {
            urn
            name
            type
            origin
            uri
            properties {
                description
            }
            platform {
                ...platformFields
            }
            platformNativeType
            ownership {
                ...ownershipFields
            }
            globalTags {
                ...globalTagsFields
            }
            glossaryTerms {
                ...glossaryTerms
            }
        }
    }
}

fragment datasetSchema on Dataset {
    schemaMetadata(version: 0) {
        ...schemaMetadataFields
    }
    editableSchemaMetadata {
        editableSchemaFieldInfo {
            fieldPath
            description
            globalTags {
                ...globalTagsFields
            }
            glossaryTerms {
                ...glossaryTerms
            }
        }
    }
}

fragment entityDetails on Entity {

  ... on Dataset {
    ...datasetSchema
    usageStats(range: MONTH) {
      buckets {
        bucket
        metrics {
          totalSqlQueries
        }
      }
      aggregations {
        uniqueUserCount
        totalSqlQueries
        fields {
          fieldName
          count
        }
      }
    }
  }
}
